version : "3"

services:
  app:
    container_name: app
    build : .
    ports:
      - "4000:6000"
    restart: always
  db:
    image: mysql
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: todolist
      MYSQL_USER: sami
      MYSQL_PASSWORD: nice
    ports:
      - '3306:3306'
    volumes:
      - ../mysql:/var/lib/mysql

